### ISSUE TITLE
React Native Explore [一]

### ISSUE THREAD

**Issue by Nbsaw** [Nbsaw/notes#36]
先下载cli 点按钮 `Building Projects with Native Code`

http://facebook.github.io/react-native/docs/getting-started.html

照着做就好了。

都很简单 唯一难的是我没有MacBook, orz,,,

打包教程也非常简单,照着这个做,设置好变量然后就好了。

http://facebook.github.io/react-native/docs/signed-apk-android.html

``` gradle
...
android {
    ...
    defaultConfig { ... }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        release {
            ...
            signingConfig signingConfigs.release
        }
    }
}
...
```

下面那个`signingConfig `别忘了,我第一次弄没太注意到,注意力集中在了上面那一块,打包出了一个没有签名的apk = = 打包出来的大小可以接受只有7MB。debug版本的大一点点。

顺便一提。如果你没有代理会很慢。如果你有的话改一下配置。`C:\Users\你的用户名\.gradle`里面的`gradle.properties`下面加两行。速度飙升。如果没有这个文件就新建一个(如果你按照教程做的话,看到这里理应应该建好了)

``` gradle
systemProp.https.proxyPort=1080
systemProp.https.proxyHost=127.0.0.1
```

ok,总之就这样可以开始探索一波RN了。整个过程非常流畅没什么阻碍,大概这就是大佬的项目吧...

PS: 本来想用vue写的就看中了阿里的weex。由于对阿里家的东西本来就有点点抵触就放弃了(其实不是因为抵触是因为点开项目看见乱七八糟,展示页面的图片还是发虚的怕了怕了)。

> you need to understand some of the basic React concepts, like JSX, components, state, and props. If you already know React, you still need to learn some React-Native-specific stuff, like the native components. 

学习RN之前要先看看React的文档。起码要知道JSX,组件,state,props之类的概念如果知道的话。剩下的就是了解一下RN特有的一些东东。

RN的文档很舒服前面还会帮你复习一下React的知识。样式之类的是用js写的。基本上要用的都有,比如`background-color`就是`backgroundColor`。采用Camel-Case命名。

我发现照着文档做的话生成的APP是一个安卓图标叫做`AwesomeProject`的东东。于是我把它换成了~~老子的形状~~我想要的样子。打开`android/app/src/rec`那个文件夹。这个文件夹是放一些资源的,`rec`是`recouses`的缩写。你会发现有好几个不同分辨率的文件夹。分别是`hdpi`,`mdpi`,`xhdpi`,`xxhdpi`里面都对应了一个图标。我们可以用Android Studio生成一个,但是我不会。于是我用了StackOverFlow老铁推荐的一个[网站](https://resizeappicon.com/)。选一张你喜欢的图片然后搞搞搞,勾上这四个分辨率的勾勾然后下载就好了。下下来替换一下名字。你还会发现有个`values`文件夹里面有个`strings.xml`里面的内容也很好懂就是你的`app_name`改成你想要的就好了。。

都弄完了就

``` shell
react-native run android
```

运行完就看得到你想要的应用图标和名字啦。

![image](https://user-images.githubusercontent.com/12481935/34646246-0ee2b8bc-f39e-11e7-8610-6ae5496d2226.png)

![image](https://user-images.githubusercontent.com/12481935/34646250-1cbb9364-f39e-11e7-9e13-246e8fd58634.png)别问我为什么不写iphone相关的,因为我没有开发环境(也不是很想搞,官網没有钦定window可以开发)...

RN支持FlexBox但是有一点点差异

> Flexbox works the same way in React Native as it does in CSS on the web, with a few exceptions. The defaults are different, with flexDirection defaulting to column instead of row, and the flex parameter only supporting a single numb

Emmmm 还行。

学习RN的主要目的是做出一个手机音乐播放器。我查了一圈官方文档并没有自带的`audio`或者`video`组件。然后就找了一个比较热门的[react-native-video](https://github.com/react-native-community/react-native-video)。音乐的API打算用[这个](https://github.com/Binaryify/NeteaseCloudMusicApi)。

刚装完`react-native-video`就报错了。

``` shell
This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ModuleResolver.resolveNodeDependency (C:\Users\nbsaw\Desktop\examples\AwesomeProject\node_modules\metro-bundler\src\node-haste\DependencyGraph\ModuleResolution.js:292:11)
    at ModuleResolution.tryResolveSync (C:\Users\nbsaw\Desktop\examples\AwesomeProject\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:103:16)
    at Object.tryResolveSync (C:\Users\nbsaw\Desktop\examples\AwesomeProject\node_modules\metro-bundler\src\node-haste\DependencyGraph\ModuleResolution.js:118:12)
....
```

让我看这条[issues](https://github.com/facebook/react-native/issues/4968)。Emmmm 试一下,让我删掉依赖。看看是否能否工作。

五分钟过去了....有点慢,如果有代理的话改改

``` shell
vim ~/.npmrc
```

加两行

``` properties
proxy = http://127.0.0.1:1080
https-proxy = http://127.0.0.1:1080
```

Boom

``` shell
C:\Users\nbsaw\Desktop\examples\AwesomeProject\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Users\nbsaw\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\nbsaw\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\nbsaw\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\nbsaw\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\nbsaw\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\nbsaw\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nbsaw\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nbsaw\Desktop\examples\AwesomeProject\node_modules\weak
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules\weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

up to date in 22.782s
```

看了下是node-gyp的问题。官网看了下原因是因为我是Python3.6不支持,只支持Python2.7..

> Python 2.7 (v3.x.x is not supported),

还要安一些其他的[东西] 很麻烦直接用[选项一](https://github.com/nodejs/node-gyp)吧 ![image](https://user-images.githubusercontent.com/12481935/34647099-c68ba4c8-f3b3-11e7-8164-2fc3c3f36850.png)

``` shell
npm install --global --production windows-build-tools
```

好了搞定。运行一下项目试试。运行正常。据其他人说这个项目是可以播放mp3的可是没有放出来。MP4倒是很正常。

好了work了 但不知道为什么... 

![image](https://user-images.githubusercontent.com/12481935/34647376-2a351042-f3bc-11e7-83c8-ec05603fecdf.png) 本地的mp3播放不出来,丢个外链却好了。暂时先不管.. 今天到这里... 明天要面试,刷刷面试题

**Comment by Nbsaw** [comment]
> you need to understand some of the basic React concepts, like JSX, components, state, and props. If you already know React, you still need to learn some React-Native-specific stuff, like the native components. 

学习RN之前要先看看React的文档。起码要知道JSX,组件,state,props之类的概念如果知道的话。剩下的就是了解一下RN特有的一些东东。

**Comment by Nbsaw** [comment]
RN支持FlexBox但是有一点点差异

> Flexbox works the same way in React Native as it does in CSS on the web, with a few exceptions. The defaults are different, with flexDirection defaulting to column instead of row, and the flex parameter only supporting a single numb

Emmmm 还行。

**Comment by Nbsaw** [comment]
面试的结果就是过了.然后面试题在[这里](https://github.com/Nbsaw/notes/issues/38)。然后因为一些原因拒绝掉了。

**Comment by Nbsaw** [comment]
R.I.P 停止更新 拖延症
